name: EnderParkour
author: CaptainDuck
version: 2.0.0
api: [2.0.0]
main: EnderParkour\Main
commands:
 enderparkour:
  description: "Main EnderParkour Command!"
  usage: "/enderparkour"
  permission: enderparkour.cmd
  aliases: [parkour, pk, parkuor]
